# Generated by Django 4.2.27 on 2025-12-25 20:24

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, unique=True)),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.FloatField()),
                ('product_manufacturing_date', models.DateField()),
                ('product_expiry_date', models.DateField()),
                ('supplier_cost', encrypted_model_fields.fields.EncryptedIntegerField(blank=True, null=True)),
                ('internal_notes', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
            ],
        ),
    ]
