# Generated by Django 4.2.27 on 2026-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='internal_notes_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_cost_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
